#!/usr/bin/env python3
"""
module/translators/config_to_prolog.py

Turns a problem's config.yaml into config_generated.pl -- plain Prolog
facts, same predicate names/arities basic_action_theory.pl used to
define inline (robot_radius/1, sigma/1, battery_start/1, the z/2 and
zbatt/1 annotated disjunctions, etc.) -- see config.yaml's own header
for the full rationale.

This mirrors an ALREADY-ESTABLISHED project pattern: occgrid_to_problog.py
generates obstacles_generated.pl from a map, and bt_to_prolog.py
generates plan_generated.pl from a BT.cpp XML tree -- both siblings of
this file in module/translators/, both writing into the SAME problem
directory this file does. config_generated.pl is a third instance of
the same "source data -> generated Prolog facts, consulted separately"
shape, just with config.yaml as the source instead of a map or a plan.

Usage:
    python3 module/translators/config_to_prolog.py
        (regenerates config_generated.pl from config.yaml, both in
        problems/problem0/ by default)

main.py calls generate() itself before every run, so you don't
normally need to run this by hand -- it's here mainly so
config_generated.pl can be regenerated/inspected on its own, and so the
generation logic has exactly one implementation.
"""
import os
import sys

import yaml

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_PROJECT_ROOT = os.path.dirname(os.path.dirname(_THIS_DIR))
_DEFAULT_PROBLEM_DIR = os.path.join(_PROJECT_ROOT, "problems", "problem0")
DEFAULT_CONFIG_PATH = os.path.join(_DEFAULT_PROBLEM_DIR, "config.yaml")
DEFAULT_OUTPUT_PATH = os.path.join(_DEFAULT_PROBLEM_DIR, "config_generated.pl")


def load_config(config_path=DEFAULT_CONFIG_PATH):
    with open(config_path) as f:
        return yaml.safe_load(f)


def _check_gaussian_weights(label, discretized_gaussian):
    total = sum(entry["weight"] for entry in discretized_gaussian)
    if abs(total - 1.0) > 1e-9:
        print(
            f"[warn] config.yaml's noise.{label}.discretized_gaussian weights "
            f"sum to {total!r}, not 1.0 -- ProbLog silently treats the missing "
            f"mass as an implicit failure branch, which will cap every "
            f"downstream probability. Fix the weights in config.yaml.",
            file=sys.stderr,
        )


def _format_number(x):
    """Preserve int vs. float formatting from the YAML source (e.g.
    battery_start(100). stays an integer fact, sigma(0.15). stays a
    float) -- Prolog's own arithmetic treats the two interchangeably,
    this is purely for the generated file to read naturally."""
    return repr(x)


def _gaussian_disjunction(functor, args_prefix, discretized_gaussian):
    """Build one annotated-disjunction block, e.g.:
        0.0606::z(do(startMoveto(CP,Triggers,T0),S), -2.0) ;
        ...
        0.0606::z(do(startMoveto(CP,Triggers,T0),S),  2.0).
    or, for a zero-argument functor like zbatt/1:
        0.0606::zbatt(-2.0) ;
        ...
        0.0606::zbatt( 2.0).
    """
    lines = []
    n = len(discretized_gaussian)
    for i, entry in enumerate(discretized_gaussian):
        weight = _format_number(entry["weight"])
        value = _format_number(entry["value"])
        head = f"{functor}({args_prefix}{value})" if args_prefix else f"{functor}({value})"
        terminator = " ;" if i < n - 1 else "."
        lines.append(f"{weight}::{head}{terminator}")
    return "\n".join(lines)


def render_prolog(config):
    _check_gaussian_weights("position", config["noise"]["position"]["discretized_gaussian"])
    _check_gaussian_weights("tangential", config["noise"]["tangential"]["discretized_gaussian"])
    _check_gaussian_weights("battery", config["noise"]["battery"]["discretized_gaussian"])

    z_block = _gaussian_disjunction(
        "z", "do(startMoveto(CP,Triggers,T0),S), ",
        config["noise"]["position"]["discretized_gaussian"])
    zt_block = _gaussian_disjunction(
        "zt", "do(startMoveto(CP,Triggers,T0),S), ",
        config["noise"]["tangential"]["discretized_gaussian"])
    zbatt_block = _gaussian_disjunction(
        "zbatt", "", config["noise"]["battery"]["discretized_gaussian"])

    lines = [
        "% AUTO-GENERATED by module/translators/config_to_prolog.py from",
        "% this problem's own config.yaml -- DO NOT HAND-EDIT, edit config.yaml",
        "% instead and regenerate (main.py does this automatically before",
        "% every run).",
        "",
        f"start({_format_number(config['initial_situation']['start_x'])},"
        f"{_format_number(config['initial_situation']['start_y'])}).",
        f"robot_radius({_format_number(config['robot']['radius'])}).",
        f"safety_buffer({_format_number(config['robot']['safety_buffer'])}).",
        f"speed({_format_number(config['motion']['speed'])}).",
        f"sigma({_format_number(config['noise']['position']['sigma'])}).",
        f"sigma_tangential({_format_number(config['noise']['tangential']['sigma'])}).",
        f"sigma_battery({_format_number(config['noise']['battery']['sigma'])}).",
        f"battery_start({_format_number(config['battery']['start'])}).",
        f"idle_drain_rate({_format_number(config['battery']['idle_drain_rate'])}).",
        f"moving_drain_rate({_format_number(config['battery']['moving_drain_rate'])}).",
        f"goal_tolerance({_format_number(config['tolerances']['goal'])}).",
        f"tolerance({_format_number(config['tolerances']['on_track'])}).",
        f"num_samples({_format_number(config['verification']['num_samples'])}).",
        f"bracket_samples({_format_number(config['verification']['bracket_samples'])}).",
        f"crossing_eps({_format_number(config['verification']['crossing_eps'])}).",
        "",
        z_block,
        "",
        zt_block,
        "",
        zbatt_block,
        "",
    ]
    return "\n".join(lines)


def generate(config_path=DEFAULT_CONFIG_PATH, output_path=DEFAULT_OUTPUT_PATH):
    config = load_config(config_path)
    text = render_prolog(config)
    with open(output_path, "w") as f:
        f.write(text)
    return output_path


if __name__ == "__main__":
    out = generate()
    print(f"Wrote {out}")
