% AUTO-GENERATED by module/translators/bt_to_prolog.py from
% behavior_tree.xml -- DO NOT HAND-EDIT,
% edit the XML tree instead and regenerate (main.py does this
% automatically before every run).
%
% Action code legend (see main.py's own printed copy of this):
%   a1: PlanWith(voronoi, goal=point(0.0,-13.5)) [MainTree]
%   a2: MoveTo(CP1) [MainTree]
%   a3: PlanWithWaypoints(straight, waypoints=[(18.5,-13.5),(18.5,0.0),(9.5,0.0)]) [MainTree]
%   a4: MoveTo(CP2) [MainTree]
%   a5: TakeSample(sample_tree_11) [MainTree]
%   a6: PlanWithWaypoints(straight, waypoints=[(0.5,0.0),(0.5,6.0),(9.5,6.0),(18.5,6.0),(18.5,13.5)]) [MainTree]
%   a7: MoveTo(CP3) [MainTree]
%   a8: PlanWithWaypoints(straight, waypoints=[(18.5,0.0),(18.5,-13.5),(0.0,-13.5)]) [MainTree]
%   a9: MoveTo(CP4) [MainTree]
%
% Condition code legend (see main.py's own printed copy of this):
%   c1: BatteryBelow(threshold=50) [MainTree]
%   c10: DistanceBelow(goal=0.0;-13.5,threshold=1.0) [MainTree]
%   c2: DistanceBelow(goal=0.0;-13.5,threshold=1.0) [MainTree]
%   c3: DistanceBelow(goal=0.0;-13.5,threshold=1.0) [MainTree]
%   c4: DistanceBelow(goal=9.5;0.0,threshold=1.0) [MainTree]
%   c5: DistanceBelow(goal=9.5;0.0,threshold=1.0) [MainTree]
%   c6: SampleValueOver(id=sample_tree_11,threshold=5.0) [MainTree]
%   c7: DistanceBelow(goal=18.5;13.5,threshold=1.0) [MainTree]
%   c8: DistanceBelow(goal=18.5;13.5,threshold=1.0) [MainTree]
%   c9: DistanceBelow(goal=0.0;-13.5,threshold=1.0) [MainTree]

plan(reactivefallback(rc1)).

% One reactive_children/2 fact per <ReactiveSequence>/
% <ReactiveFallback> in the tree, keyed by the same code
% embedded in plan/1's own reactivesequence(Code)/
% reactivefallback(Code) markers above -- see basic_action_
% theory.pl's own CONTROL-FLOW REDESCEND TARGETS note for why
% these live as SEPARATE facts rather than being inlined.

reactive_children(rc1, [seq_node([cond(battery_below(50.0),c1),fallback_node([cond(distance_below(0.0,-13.5,1.0),c2),seq_node([planWith(voronoi,point(0.0,-13.5),CP1,a1),moveto_leg(CP1,[collision,battery],a2),cond(distance_below(0.0,-13.5,1.0),c3)])])]),seq_node([fallback_node([cond(distance_below(9.5,0.0,1.0),c4),seq_node([planWithWaypoints(straight,[point(18.5,-13.5),point(18.5,0.0),point(9.5,0.0)],CP2,a3),moveto_leg(CP2,[collision,battery],a4),cond(distance_below(9.5,0.0,1.0),c5)])]),take_sample(sample_tree_11,a5),fallback_node([seq_node([cond(sample_value_over(sample_tree_11,5.0),c6),fallback_node([cond(distance_below(18.5,13.5,1.0),c7),seq_node([planWithWaypoints(straight,[point(0.5,0.0),point(0.5,6.0),point(9.5,6.0),point(18.5,6.0),point(18.5,13.5)],CP3,a6),moveto_leg(CP3,[collision,battery],a7),cond(distance_below(18.5,13.5,1.0),c8)])])]),fallback_node([cond(distance_below(0.0,-13.5,1.0),c9),seq_node([planWithWaypoints(straight,[point(18.5,0.0),point(18.5,-13.5),point(0.0,-13.5)],CP4,a8),moveto_leg(CP4,[collision,battery],a9),cond(distance_below(0.0,-13.5,1.0),c10)])])])])]).
