% AUTO-GENERATED by module/translators/bt_to_prolog.py from
% behavior_tree.xml -- DO NOT HAND-EDIT,
% edit the XML tree instead and regenerate (main.py does this
% automatically before every run).
%
% Action code legend (see main.py's own printed copy of this):
%   a1: PlanWith(straight, goal=point(32.0,-27.0))
%   a2: MoveTo(CP2__SUB1)
%   a3: TakeSample(sample_tree_11)
%   a4: PlanWith(straight, goal=point(32.0,-27.0))
%   a5: MoveTo(CP2__SUB2)
%   a6: TakeSample(sample_tree_11)
%   a7: PlanWith(straight, goal=point(32.0,-27.0))
%   a8: MoveTo(CP2__SUB3)
%   a9: TakeSample(sample_tree_11)
%
% Condition code legend (see main.py's own printed copy of this):
%   c1: DistanceBelow(goal=32.0;-27.0,threshold=1.0)
%   c2: DistanceBelow(goal=32.0;-27.0,threshold=1.0)
%   c3: DistanceBelow(goal=32.0;-27.0,threshold=1.0)
%   c4: DistanceBelow(goal=32.0;-27.0,threshold=1.0)
%   c5: DistanceBelow(goal=32.0;-27.0,threshold=1.0)
%   c6: DistanceBelow(goal=32.0;-27.0,threshold=1.0)

plan(fallback_node([seq_node([fallback_node([cond(distance_below(32.0,-27.0,1.0),c1),seq_node([planWith(straight,point(32.0,-27.0),CP2__SUB1,a1),moveto_leg(CP2__SUB1,[collision,battery],a2),cond(distance_below(32.0,-27.0,1.0),c2)])]),take_sample(sample_tree_11,a3)]),seq_node([fallback_node([cond(distance_below(32.0,-27.0,1.0),c3),seq_node([planWith(straight,point(32.0,-27.0),CP2__SUB2,a4),moveto_leg(CP2__SUB2,[collision,battery],a5),cond(distance_below(32.0,-27.0,1.0),c4)])]),take_sample(sample_tree_11,a6)]),seq_node([fallback_node([cond(distance_below(32.0,-27.0,1.0),c5),seq_node([planWith(straight,point(32.0,-27.0),CP2__SUB3,a7),moveto_leg(CP2__SUB3,[collision,battery],a8),cond(distance_below(32.0,-27.0,1.0),c6)])]),take_sample(sample_tree_11,a9)])])).
