% AUTO-GENERATED by module/translators/bt_to_prolog.py from
% behavior_tree.xml -- DO NOT HAND-EDIT,
% edit the XML tree instead and regenerate (main.py does this
% automatically before every run).
%
% Action code legend (see main.py's own printed copy of this):
%   a1: PlanWithWaypoints(straight, waypoints=[(24.0,-4.5),(32.0,-4.5),(32.0,-27.0)]) [MainTree]
%   a10: MoveTo(CP2__SUB3) [MainTree]
%   a11: TakeSample(sample_tree_11) [MainTree]
%   a2: MoveTo(CP1) [MainTree]
%   a3: PlanWith(straight, goal=point(45.5,-31.5)) [MainTree]
%   a4: MoveTo(CP2__SUB1) [MainTree]
%   a5: TakeSample(sample_tree_11) [MainTree]
%   a6: PlanWith(straight, goal=point(45.5,-31.5)) [MainTree]
%   a7: MoveTo(CP2__SUB2) [MainTree]
%   a8: TakeSample(sample_tree_11) [MainTree]
%   a9: PlanWith(straight, goal=point(45.5,-31.5)) [MainTree]
%
% Condition code legend (see main.py's own printed copy of this):
%   c1: DistanceBelow(goal=32.0;-27.0,threshold=1.0) [MainTree]
%   c2: DistanceBelow(goal=32.0;-27.0,threshold=1.0) [MainTree]
%   c3: DistanceBelow(goal=45.5;-31.5,threshold=1.0) [MainTree]
%   c4: DistanceBelow(goal=45.5;-31.5,threshold=1.0) [MainTree]
%   c5: DistanceBelow(goal=45.5;-31.5,threshold=1.0) [MainTree]
%   c6: DistanceBelow(goal=45.5;-31.5,threshold=1.0) [MainTree]
%   c7: DistanceBelow(goal=45.5;-31.5,threshold=1.0) [MainTree]
%   c8: DistanceBelow(goal=45.5;-31.5,threshold=1.0) [MainTree]

plan(seq_node([fallback_node([cond(distance_below(32.0,-27.0,1.0),c1),seq_node([planWithWaypoints(straight,[point(24.0,-4.5),point(32.0,-4.5),point(32.0,-27.0)],CP1,a1),moveto_leg(CP1,[collision,battery],a2),cond(distance_below(32.0,-27.0,1.0),c2)])]),fallback_node([seq_node([fallback_node([cond(distance_below(45.5,-31.5,1.0),c3),seq_node([planWith(straight,point(45.5,-31.5),CP2__SUB1,a3),moveto_leg(CP2__SUB1,[collision,battery],a4),cond(distance_below(45.5,-31.5,1.0),c4)])]),take_sample(sample_tree_11,a5)]),seq_node([fallback_node([cond(distance_below(45.5,-31.5,1.0),c5),seq_node([planWith(straight,point(45.5,-31.5),CP2__SUB2,a6),moveto_leg(CP2__SUB2,[collision,battery],a7),cond(distance_below(45.5,-31.5,1.0),c6)])]),take_sample(sample_tree_11,a8)]),seq_node([fallback_node([cond(distance_below(45.5,-31.5,1.0),c7),seq_node([planWith(straight,point(45.5,-31.5),CP2__SUB3,a9),moveto_leg(CP2__SUB3,[collision,battery],a10),cond(distance_below(45.5,-31.5,1.0),c8)])]),take_sample(sample_tree_11,a11)])])])).
