% AUTO-GENERATED by occgrid_to_problog.py -- do not hand-edit.
% Source map: /home/user/BT_project/problems/problem5/map.yaml
% obstacle_polygon(Id, [point(X,Y), ...]) -- vertices in metres,
% map frame, consistent with the source OccupancyGrid's origin.
% Pre-inflated by 0.3000m (robot_radius+safety_buffer,
% this problem's own config.yaml -- see basic_action_theory.pl's
% own safety_margin/1 note): every polygon below is the ROBOT'S
% OWN safety-inflated obstacle boundary, not the map's raw occupied
% cells. This is the ONLY obstacle geometry generated for this
% problem -- collision_geometry.py AND every planner in
% module/theory/planners.py (plan_astar, plan_voronoi,
% follow_boarder) all read this SAME already-inflated set; see
% planners.py's own module docstring for how follow_boarder
% corrects its own Offset argument for the inflation already
% baked in here.
% 1 obstacle region(s) extracted.

obstacle_polygon(obs1, [point(-4.5005,49.9995), point(-4.6005,49.7995), point(-4.6005,11.1995), point(-4.8005,11.0995), point(-4.9005,10.8995), point(-4.9005,10.2995), point(-4.8005,10.0995), point(-4.6005,9.9995), point(-4.6005,-21.4005), point(-4.8005,-21.5005), point(-4.9005,-21.7005), point(-4.9005,-22.3005), point(-4.8005,-22.5005), point(-4.6005,-22.6005), point(-4.6005,-49.8005), point(-4.5005,-50.0005), point(-4.3005,-50.1005), point(50.2995,-50.1005), point(50.4995,-50.0005), point(50.5995,-49.8005), point(50.5995,49.6995), point(50.4995,49.8995), point(50.1995,50.0995), point(-4.3005,50.0995)]).
