% AUTO-GENERATED by module/translators/bt_to_prolog.py from
% behavior_tree.xml -- DO NOT HAND-EDIT,
% edit the XML tree instead and regenerate (main.py does this
% automatically before every run).
%
% Action code legend (see main.py's own printed copy of this):
%   a1: PlanWithWaypoints(astar, waypoints=[(0.5,0.0),(29.5,4.5)]) [MainTree]
%   a10: MoveTo(CP3__SUB3) [MainTree]
%   a11: TakeSample(sample_tree_11) [MainTree]
%   a12: PlanWithWaypoints(astar, waypoints=[(29.5,13.5),(17.0,18.0),(29.5,22.5)]) [MainTree]
%   a13: MoveTo(__MERGED_CP_2) [MainTree]
%   a14: PlanWith(astar, goal=point(17.0,27.0)) [MainTree]
%   a15: MoveTo(CP7__SUB4) [MainTree]
%   a16: TakeSample(sample_tree_53) [MainTree]
%   a17: PlanWith(astar, goal=point(17.0,27.0)) [MainTree]
%   a18: MoveTo(CP7__SUB5) [MainTree]
%   a19: TakeSample(sample_tree_53) [MainTree]
%   a2: MoveTo(__MERGED_CP_1) [MainTree]
%   a20: PlanWith(astar, goal=point(17.0,27.0)) [MainTree]
%   a21: MoveTo(CP7__SUB6) [MainTree]
%   a22: TakeSample(sample_tree_53) [MainTree]
%   a23: PlanWith(astar, goal=point(9.0,27.0)) [MainTree]
%   a24: MoveTo(CP8) [MainTree]
%   a3: PlanWith(astar, goal=point(17.0,9.0)) [MainTree]
%   a4: MoveTo(CP3__SUB1) [MainTree]
%   a5: TakeSample(sample_tree_11) [MainTree]
%   a6: PlanWith(astar, goal=point(17.0,9.0)) [MainTree]
%   a7: MoveTo(CP3__SUB2) [MainTree]
%   a8: TakeSample(sample_tree_11) [MainTree]
%   a9: PlanWith(astar, goal=point(17.0,9.0)) [MainTree]

plan(seq_node([seq_node([planWithWaypoints(astar,[point(0.5,0.0),point(29.5,4.5)],__MERGED_CP_1,a1),moveto_leg(__MERGED_CP_1,[collision,battery],a2)]),fallback_node([seq_node([seq_node([planWith(astar,point(17.0,9.0),CP3__SUB1,a3),moveto_leg(CP3__SUB1,[collision,battery],a4)]),take_sample(sample_tree_11,a5)]),seq_node([seq_node([planWith(astar,point(17.0,9.0),CP3__SUB2,a6),moveto_leg(CP3__SUB2,[collision,battery],a7)]),take_sample(sample_tree_11,a8)]),seq_node([seq_node([planWith(astar,point(17.0,9.0),CP3__SUB3,a9),moveto_leg(CP3__SUB3,[collision,battery],a10)]),take_sample(sample_tree_11,a11)])]),seq_node([planWithWaypoints(astar,[point(29.5,13.5),point(17.0,18.0),point(29.5,22.5)],__MERGED_CP_2,a12),moveto_leg(__MERGED_CP_2,[collision,battery],a13)]),fallback_node([seq_node([seq_node([planWith(astar,point(17.0,27.0),CP7__SUB4,a14),moveto_leg(CP7__SUB4,[collision,battery],a15)]),take_sample(sample_tree_53,a16)]),seq_node([seq_node([planWith(astar,point(17.0,27.0),CP7__SUB5,a17),moveto_leg(CP7__SUB5,[collision,battery],a18)]),take_sample(sample_tree_53,a19)]),seq_node([seq_node([planWith(astar,point(17.0,27.0),CP7__SUB6,a20),moveto_leg(CP7__SUB6,[collision,battery],a21)]),take_sample(sample_tree_53,a22)])]),seq_node([planWith(astar,point(9.0,27.0),CP8,a23),moveto_leg(CP8,[collision,battery],a24)])])).
