% AUTO-GENERATED by module/translators/bt_to_prolog.py from
% behavior_tree.xml -- DO NOT HAND-EDIT,
% edit the XML tree instead and regenerate (main.py does this
% automatically before every run).
%
% Action code legend (see main.py's own printed copy of this):
%   a1: NearestToolOfKind(cart) [install_closest_cart]
%   a2: PlanWith(dastar(2.0), goal={cartposition__sub1}) [install_closest_cart]
%   a3: MoveTo(CP__SUB1) [install_closest_cart]
%   a4: InstallTool({cartid__sub1}) [install_closest_cart]
%   a5: HitchedId [uninstall_cart]
%   a6: PlanWith(dastar(2.0), goal=point(22.0,-15.0)) [uninstall_cart]
%   a7: MoveTo(CP__SUB2) [uninstall_cart]
%   a8: UninstallTool({tool__sub2}) [uninstall_cart]
%
% Condition code legend (see main.py's own printed copy of this):
%   c1: Hitched(kind=cart) [install_closest_cart]
%   c2: DistanceBelow(goal={cartposition__sub1},threshold=1.0) [install_closest_cart]
%   c3: DistanceBelow(goal={cartposition__sub1},threshold=1.0) [install_closest_cart]
%   c4: Hitched() [uninstall_cart]
%   c5: DistanceBelow(goal=22.0;-15.0,threshold=1.0) [uninstall_cart]
%   c6: DistanceBelow(goal=22.0;-15.0,threshold=1.0) [uninstall_cart]

plan(seq_node([fallback_node([cond(hitched(cart),c1),seq_node([nearest_tool_of_kind_query(cart,CARTID__SUB1,CARTPOSITION__SUB1,a1),fallback_node([cond(distance_below(CARTPOSITION__SUB1,1.0),c2),seq_node([planWith(dastar(2.0),CARTPOSITION__SUB1,CP__SUB1,a2),moveto_leg(CP__SUB1,[collision,battery],a3),cond(distance_below(CARTPOSITION__SUB1,1.0),c3)])]),install_tool_leg(CARTID__SUB1,[battery],a4)])]),fallback_node([inverter(cond(hitched,c4)),seq_node([hitched_id_query(TOOL__SUB2,a5),fallback_node([cond(distance_below(22.0,-15.0,1.0),c5),seq_node([planWith(dastar(2.0),point(22.0,-15.0),CP__SUB2,a6),moveto_leg(CP__SUB2,[collision,battery],a7),cond(distance_below(22.0,-15.0,1.0),c6)])]),uninstall_tool_leg(TOOL__SUB2,[battery],a8)])])])).
