% AUTO-GENERATED by module/contracts/goal_formula_check.py's
% generate_safety_queries -- DO NOT HAND-EDIT, this is derived
% entirely from the problem's own behavior_tree.xml (via
% bt_to_prolog.py) and regenerated by main.py before every run.

query(verify_goal_formula).
query(plan_outcome(true)).
query(plan_outcome(false)).
query(plan_outcome(world_too_large)).
query(plan_outcome(reactive_escaped)).
query(outcome_signature(_)).

query(any_reason_pattern(battery_depleted)).
query(any_reason_pattern(completed)).
query(any_reason_pattern(completed(dastar(2.0),point(22.0,-15.0)))).
query(any_reason_pattern(completed(dastar(2.0),wild))).
query(any_reason_pattern(crashed(wild))).
query(any_reason_pattern(hitched_id_found(wild))).
query(any_reason_pattern(hitched_id_unavailable)).
query(any_reason_pattern(install_tool_failure(wild))).
query(any_reason_pattern(install_tool_success(wild))).
query(any_reason_pattern(nearest_tool_found(cart,wild))).
query(any_reason_pattern(no_path(dastar(2.0),point(22.0,-15.0)))).
query(any_reason_pattern(no_path(dastar(2.0),wild))).
query(any_reason_pattern(no_tool_of_kind(cart))).
query(any_reason_pattern(uninstall_tool_failure(wild))).
query(any_reason_pattern(uninstall_tool_success(wild))).

query(any_reason_pattern_by_action(nearest_tool_found(cart,wild),a1)).
query(any_reason_pattern_detail_by_action(nearest_tool_found(cart,_),a1)).
query(any_reason_pattern_by_action(no_tool_of_kind(cart),a1)).
query(any_reason_pattern_by_action(completed(dastar(2.0),wild),a2)).
query(any_reason_pattern_detail_by_action(completed(dastar(2.0),_),a2)).
query(any_reason_pattern_by_action(no_path(dastar(2.0),wild),a2)).
query(any_reason_pattern_detail_by_action(no_path(dastar(2.0),_),a2)).
query(any_reason_pattern_by_action(completed,a3)).
query(any_reason_pattern_by_action(crashed(wild),a3)).
query(any_reason_pattern_detail_by_action(crashed(_),a3)).
query(any_reason_pattern_by_action(battery_depleted,a3)).
query(any_reason_pattern_by_action(install_tool_success(wild),a4)).
query(any_reason_pattern_detail_by_action(install_tool_success(_),a4)).
query(any_reason_pattern_by_action(install_tool_failure(wild),a4)).
query(any_reason_pattern_detail_by_action(install_tool_failure(_),a4)).
query(any_reason_pattern_by_action(battery_depleted,a4)).
query(any_reason_pattern_by_action(hitched_id_found(wild),a5)).
query(any_reason_pattern_detail_by_action(hitched_id_found(_),a5)).
query(any_reason_pattern_by_action(hitched_id_unavailable,a5)).
query(any_reason_pattern_by_action(completed(dastar(2.0),point(22.0,-15.0)),a6)).
query(any_reason_pattern_by_action(no_path(dastar(2.0),point(22.0,-15.0)),a6)).
query(any_reason_pattern_by_action(completed,a7)).
query(any_reason_pattern_by_action(crashed(wild),a7)).
query(any_reason_pattern_detail_by_action(crashed(_),a7)).
query(any_reason_pattern_by_action(battery_depleted,a7)).
query(any_reason_pattern_by_action(uninstall_tool_success(wild),a8)).
query(any_reason_pattern_detail_by_action(uninstall_tool_success(_),a8)).
query(any_reason_pattern_by_action(uninstall_tool_failure(wild),a8)).
query(any_reason_pattern_detail_by_action(uninstall_tool_failure(_),a8)).
query(any_reason_pattern_by_action(battery_depleted,a8)).

query(any_condition_status(c1,true)).
query(any_condition_status(c1,false)).
query(any_condition_status(c2,true)).
query(any_condition_status(c2,false)).
query(any_condition_status(c3,true)).
query(any_condition_status(c3,false)).
query(any_condition_status(c4,true)).
query(any_condition_status(c4,false)).
query(any_condition_status(c5,true)).
query(any_condition_status(c5,false)).
query(any_condition_status(c6,true)).
query(any_condition_status(c6,false)).
