% AUTO-GENERATED by module/translators/bt_to_prolog.py from
% behavior_tree.xml -- DO NOT HAND-EDIT,
% edit the XML tree instead and regenerate (main.py does this
% automatically before every run).
%
% Action code legend (see main.py's own printed copy of this):
%   a1: PlanWithWaypoints(straight, waypoints=[(24.0,-4.5),(32.0,-4.5)]) [MainTree]
%   a10: MoveTo(CP3) [MainTree]
%   a11: TakeSample(sample_tree_11) [MainTree]
%   a12: PlanWithWaypoints(straight, waypoints=[(45.5,-31.5),(23.0,-36.0),(0.5,-31.5)]) [MainTree]
%   a13: MoveTo(__MERGED_CP_2) [MainTree]
%   a14: PlanWith(straight, goal=point(32.0,-4.5)) [MainTree]
%   a15: MoveTo(CP7) [MainTree]
%   a16: TakeSample(sample_tree_53) [MainTree]
%   a17: PlanWith(straight, goal=point(32.0,-4.5)) [MainTree]
%   a18: MoveTo(CP7) [MainTree]
%   a19: TakeSample(sample_tree_53) [MainTree]
%   a2: MoveTo(__MERGED_CP_1) [MainTree]
%   a20: PlanWith(straight, goal=point(32.0,-4.5)) [MainTree]
%   a21: MoveTo(CP7) [MainTree]
%   a22: TakeSample(sample_tree_53) [MainTree]
%   a23: PlanWith(straight, goal=point(11.3,-15.0)) [MainTree]
%   a24: MoveTo(CP8) [MainTree]
%   a3: PlanWith(straight, goal=point(32.0,-27.0)) [MainTree]
%   a4: MoveTo(CP3) [MainTree]
%   a5: TakeSample(sample_tree_11) [MainTree]
%   a6: PlanWith(straight, goal=point(32.0,-27.0)) [MainTree]
%   a7: MoveTo(CP3) [MainTree]
%   a8: TakeSample(sample_tree_11) [MainTree]
%   a9: PlanWith(straight, goal=point(32.0,-27.0)) [MainTree]

plan(seq_node([seq_node([planWithWaypoints(straight,[point(24.0,-4.5),point(32.0,-4.5)],__MERGED_CP_1,a1),moveto_leg(__MERGED_CP_1,[collision,battery],a2)]),fallback_node([seq_node([seq_node([planWith(straight,point(32.0,-27.0),CP3,a3),moveto_leg(CP3,[collision,battery],a4)]),take_sample(sample_tree_11,a5)]),seq_node([seq_node([planWith(straight,point(32.0,-27.0),CP3,a6),moveto_leg(CP3,[collision,battery],a7)]),take_sample(sample_tree_11,a8)]),seq_node([seq_node([planWith(straight,point(32.0,-27.0),CP3,a9),moveto_leg(CP3,[collision,battery],a10)]),take_sample(sample_tree_11,a11)])]),seq_node([planWithWaypoints(straight,[point(45.5,-31.5),point(23.0,-36.0),point(0.5,-31.5)],__MERGED_CP_2,a12),moveto_leg(__MERGED_CP_2,[collision,battery],a13)]),fallback_node([seq_node([seq_node([planWith(straight,point(32.0,-4.5),CP7,a14),moveto_leg(CP7,[collision,battery],a15)]),take_sample(sample_tree_53,a16)]),seq_node([seq_node([planWith(straight,point(32.0,-4.5),CP7,a17),moveto_leg(CP7,[collision,battery],a18)]),take_sample(sample_tree_53,a19)]),seq_node([seq_node([planWith(straight,point(32.0,-4.5),CP7,a20),moveto_leg(CP7,[collision,battery],a21)]),take_sample(sample_tree_53,a22)])]),seq_node([planWith(straight,point(11.3,-15.0),CP8,a23),moveto_leg(CP8,[collision,battery],a24)])])).
