% AUTO-GENERATED by module/translators/bt_to_prolog.py from
% behavior_tree.xml -- DO NOT HAND-EDIT,
% edit the XML tree instead and regenerate (main.py does this
% automatically before every run).
%
% Action code legend (see main.py's own printed copy of this):
%   a1: PlanWith(astar, goal=point(24.0,-4.5)) [MainTree]
%   a10: TakeSample(sample_tree_11) [MainTree]
%   a11: PlanWith(astar, goal=point(32.0,-27.0)) [MainTree]
%   a12: MoveTo(CP3) [MainTree]
%   a13: TakeSample(sample_tree_11) [MainTree]
%   a14: PlanWith(astar, goal=point(45.5,-31.5)) [MainTree]
%   a15: MoveTo(CP4) [MainTree]
%   a16: PlanWith(astar, goal=point(23.0,-36.0)) [MainTree]
%   a17: MoveTo(CP5) [MainTree]
%   a18: PlanWith(astar, goal=point(0.5,-31.5)) [MainTree]
%   a19: MoveTo(CP6) [MainTree]
%   a2: MoveTo(CP1) [MainTree]
%   a20: PlanWith(astar, goal=point(32.0,-4.5)) [MainTree]
%   a21: MoveTo(CP7) [MainTree]
%   a22: TakeSample(sample_tree_53) [MainTree]
%   a23: PlanWith(astar, goal=point(32.0,-4.5)) [MainTree]
%   a24: MoveTo(CP7) [MainTree]
%   a25: TakeSample(sample_tree_53) [MainTree]
%   a26: PlanWith(astar, goal=point(32.0,-4.5)) [MainTree]
%   a27: MoveTo(CP7) [MainTree]
%   a28: TakeSample(sample_tree_53) [MainTree]
%   a29: PlanWith(astar, goal=point(11.3,-15.0)) [MainTree]
%   a3: PlanWith(astar, goal=point(32.0,-4.5)) [MainTree]
%   a30: MoveTo(CP8) [MainTree]
%   a4: MoveTo(CP2) [MainTree]
%   a5: PlanWith(astar, goal=point(32.0,-27.0)) [MainTree]
%   a6: MoveTo(CP3) [MainTree]
%   a7: TakeSample(sample_tree_11) [MainTree]
%   a8: PlanWith(astar, goal=point(32.0,-27.0)) [MainTree]
%   a9: MoveTo(CP3) [MainTree]
%
% Condition code legend (see main.py's own printed copy of this):
%   c1: DistanceBelow(goal=24.0;-4.5,threshold=0.3) [MainTree]
%   c10: DistanceBelow(goal=32.0;-4.5,threshold=0.3) [MainTree]
%   c11: DistanceBelow(goal=32.0;-4.5,threshold=0.3) [MainTree]
%   c12: DistanceBelow(goal=11.3;-15.0,threshold=0.3) [MainTree]
%   c2: DistanceBelow(goal=32.0;-4.5,threshold=0.3) [MainTree]
%   c3: DistanceBelow(goal=32.0;-27.0,threshold=0.3) [MainTree]
%   c4: DistanceBelow(goal=32.0;-27.0,threshold=0.3) [MainTree]
%   c5: DistanceBelow(goal=32.0;-27.0,threshold=0.3) [MainTree]
%   c6: DistanceBelow(goal=45.5;-31.5,threshold=0.3) [MainTree]
%   c7: DistanceBelow(goal=23.0;-36.0,threshold=0.3) [MainTree]
%   c8: DistanceBelow(goal=0.5;-31.5,threshold=0.3) [MainTree]
%   c9: DistanceBelow(goal=32.0;-4.5,threshold=0.3) [MainTree]

plan(seq_node([seq_node([planWith(astar,point(24.0,-4.5),CP1,a1),moveto_leg(CP1,[collision,battery],a2),cond(distance_below(24.0,-4.5,0.3),c1)]),seq_node([planWith(astar,point(32.0,-4.5),CP2,a3),moveto_leg(CP2,[collision,battery],a4),cond(distance_below(32.0,-4.5,0.3),c2)]),fallback_node([seq_node([seq_node([planWith(astar,point(32.0,-27.0),CP3,a5),moveto_leg(CP3,[collision,battery],a6),cond(distance_below(32.0,-27.0,0.3),c3)]),take_sample(sample_tree_11,a7)]),seq_node([seq_node([planWith(astar,point(32.0,-27.0),CP3,a8),moveto_leg(CP3,[collision,battery],a9),cond(distance_below(32.0,-27.0,0.3),c4)]),take_sample(sample_tree_11,a10)]),seq_node([seq_node([planWith(astar,point(32.0,-27.0),CP3,a11),moveto_leg(CP3,[collision,battery],a12),cond(distance_below(32.0,-27.0,0.3),c5)]),take_sample(sample_tree_11,a13)])]),seq_node([planWith(astar,point(45.5,-31.5),CP4,a14),moveto_leg(CP4,[collision,battery],a15),cond(distance_below(45.5,-31.5,0.3),c6)]),seq_node([planWith(astar,point(23.0,-36.0),CP5,a16),moveto_leg(CP5,[collision,battery],a17),cond(distance_below(23.0,-36.0,0.3),c7)]),seq_node([planWith(astar,point(0.5,-31.5),CP6,a18),moveto_leg(CP6,[collision,battery],a19),cond(distance_below(0.5,-31.5,0.3),c8)]),fallback_node([seq_node([seq_node([planWith(astar,point(32.0,-4.5),CP7,a20),moveto_leg(CP7,[collision,battery],a21),cond(distance_below(32.0,-4.5,0.3),c9)]),take_sample(sample_tree_53,a22)]),seq_node([seq_node([planWith(astar,point(32.0,-4.5),CP7,a23),moveto_leg(CP7,[collision,battery],a24),cond(distance_below(32.0,-4.5,0.3),c10)]),take_sample(sample_tree_53,a25)]),seq_node([seq_node([planWith(astar,point(32.0,-4.5),CP7,a26),moveto_leg(CP7,[collision,battery],a27),cond(distance_below(32.0,-4.5,0.3),c11)]),take_sample(sample_tree_53,a28)])]),seq_node([planWith(astar,point(11.3,-15.0),CP8,a29),moveto_leg(CP8,[collision,battery],a30),cond(distance_below(11.3,-15.0,0.3),c12)])])).
