% AUTO-GENERATED by module/translators/config_to_prolog.py from
% this problem's own config.yaml -- DO NOT HAND-EDIT, edit config.yaml
% instead and regenerate (main.py does this automatically before
% every run).

start(2.275,2.075).
robot_radius(0.2).
safety_buffer(0.1).
speed(1.0).
sigma(0.15).
sigma_tangential(0.15).
sigma_battery(0.5).
battery_start(100).
idle_drain_rate(0.05).
moving_drain_rate(5.0).
goal_tolerance(0.3).
tolerance(0.5).
num_samples(20).
bracket_samples(60).
crossing_eps(0.01).

0.0606::z(do(startMoveto(CP,Triggers,T0),S), -2.0) ;
0.2417::z(do(startMoveto(CP,Triggers,T0),S), -1.0) ;
0.3954::z(do(startMoveto(CP,Triggers,T0),S), 0.0) ;
0.2417::z(do(startMoveto(CP,Triggers,T0),S), 1.0) ;
0.0606::z(do(startMoveto(CP,Triggers,T0),S), 2.0).

0.0606::zt(do(startMoveto(CP,Triggers,T0),S), -2.0) ;
0.2417::zt(do(startMoveto(CP,Triggers,T0),S), -1.0) ;
0.3954::zt(do(startMoveto(CP,Triggers,T0),S), 0.0) ;
0.2417::zt(do(startMoveto(CP,Triggers,T0),S), 1.0) ;
0.0606::zt(do(startMoveto(CP,Triggers,T0),S), 2.0).

0.0606::zbatt(-2.0) ;
0.2417::zbatt(-1.0) ;
0.3954::zbatt(0.0) ;
0.2417::zbatt(1.0) ;
0.0606::zbatt(2.0).
