% AUTO-GENERATED by module/translators/config_to_prolog.py from
% this problem's own config.yaml -- DO NOT HAND-EDIT, edit config.yaml
% instead and regenerate (main.py does this automatically before
% every run).

start(12.6,0.0).
robot_radius(0.2).
safety_buffer(0.1).
speed(1.0).
sigma(0.15).
sigma_tangential(0.15).
disc_step_position(1.0).
battery_enabled(true).
sigma_battery(0.5).
battery_start(100).
idle_drain_rate(0.05).
moving_drain_rate(5.0).
disc_step_battery(10).
tolerance(0.5).
num_samples(20).
bracket_samples(60).
crossing_eps(0.01).
disc_step_time(20).

0.25::z(do(startMoveto(CP,Triggers,ActionCode,T0),S), -1.0) ;
0.5::z(do(startMoveto(CP,Triggers,ActionCode,T0),S), 0.0) ;
0.25::z(do(startMoveto(CP,Triggers,ActionCode,T0),S), 1.0).

0.25::zt(do(startMoveto(CP,Triggers,ActionCode,T0),S), -1.0) ;
0.5::zt(do(startMoveto(CP,Triggers,ActionCode,T0),S), 0.0) ;
0.25::zt(do(startMoveto(CP,Triggers,ActionCode,T0),S), 1.0).

0.25::zbatt(-1.0) ;
0.5::zbatt(0.0) ;
0.25::zbatt(1.0).

0.5::sample_result(S,ActionCode,true) ;
0.5::sample_result(S,ActionCode,false).

0.012224472655044727::sample_value(S,ActionCode,0) ;
0.027834684208772387::sample_value(S,ActionCode,1) ;
0.06559061680303818::sample_value(S,ActionCode,2) ;
0.12097757871001291::sample_value(S,ActionCode,3) ;
0.1746663219402081::sample_value(S,ActionCode,4) ;
0.1974126513658474::sample_value(S,ActionCode,5) ;
0.17466632194020804::sample_value(S,ActionCode,6) ;
0.12097757871001291::sample_value(S,ActionCode,7) ;
0.06559061680303824::sample_value(S,ActionCode,8) ;
0.027834684208772442::sample_value(S,ActionCode,9) ;
0.012224472655044671::sample_value(S,ActionCode,10).

install_tool_duration(cart, 10.0).
install_tool_duration(plow, 10.0).
uninstall_tool_duration(cart, 10.0).
uninstall_tool_duration(plow, 10.0).
install_tool_drain_rate(0.05).
uninstall_tool_drain_rate(0.05).
install_tool_range(0.3).

0.9::install_tool_result(S,ActionCode,true) ;
0.09999999999999998::install_tool_result(S,ActionCode,false).

0.9::uninstall_tool_result(S,ActionCode,true) ;
0.09999999999999998::uninstall_tool_result(S,ActionCode,false).

tool_speed(free, 1.0).
tool_speed(cart, 1.0).
tool_speed(plow, 1.0).

tool_moving_drain_rate(free, 5.0).
tool_moving_drain_rate(cart, 5.0).
tool_moving_drain_rate(plow, 5.0).

query(any_battery_depletion).
