% AUTO-GENERATED by module/translators/moveto_outcomes_to_prolog.py
% -- DO NOT HAND-EDIT, edit behavior_tree.xml/config.yaml and
% regenerate instead. See basic_action_theory.pl Section 2 for the
% moveto_outcome/7 interface this file implements, and that
% module's own header for how (LegId,InBranch) pairs were
% determined (a symbolic BFS over the plan's own Fallback/Sequence
% semantics, NOT observed from ProbLog's grounder).

0.00367236::moveto_outcome(leg_try_goal, root, p1, success, point(20.933359213500125,0.7333592135001263), 20.0, 100.0) ;
0.01464702::moveto_outcome(leg_try_goal, root, p2, success, point(21.604179606750062,0.7333592135001263), 20.0, 100.0) ;
0.02396124::moveto_outcome(leg_try_goal, root, p3, success, point(22.275,0.7333592135001263), 20.0, 100.0) ;
0.01464702::moveto_outcome(leg_try_goal, root, p4, success, point(22.945820393249935,0.7333592135001263), 20.0, 100.0) ;
0.00367236::moveto_outcome(leg_try_goal, root, p5, success, point(23.61664078649987,0.7333592135001263), 20.0, 100.0) ;
0.01464702::moveto_outcome(leg_try_goal, root, p6, success, point(20.933359213500125,1.4041796067500631), 20.0, 100.0) ;
0.05841889::moveto_outcome(leg_try_goal, root, p7, success, point(21.604179606750062,1.4041796067500631), 20.0, 100.0) ;
0.09556818::moveto_outcome(leg_try_goal, root, p8, success, point(22.275,1.4041796067500631), 20.0, 100.0) ;
0.05841889::moveto_outcome(leg_try_goal, root, p9, success, point(22.945820393249935,1.4041796067500631), 20.0, 100.0) ;
0.01464702::moveto_outcome(leg_try_goal, root, p10, success, point(23.61664078649987,1.4041796067500631), 20.0, 100.0) ;
0.02396124::moveto_outcome(leg_try_goal, root, p11, success, point(20.933359213500125,2.075), 20.0, 100.0) ;
0.09556818::moveto_outcome(leg_try_goal, root, p12, success, point(21.604179606750062,2.075), 20.0, 100.0) ;
0.15634116::moveto_outcome(leg_try_goal, root, p13, success, point(22.275,2.075), 20.0, 100.0) ;
0.09556818::moveto_outcome(leg_try_goal, root, p14, success, point(22.945820393249935,2.075), 20.0, 100.0) ;
0.02396124::moveto_outcome(leg_try_goal, root, p15, success, point(23.61664078649987,2.075), 20.0, 100.0) ;
0.01464702::moveto_outcome(leg_try_goal, root, p16, success, point(20.933359213500125,2.745820393249937), 20.0, 100.0) ;
0.05841889::moveto_outcome(leg_try_goal, root, p17, success, point(21.604179606750062,2.745820393249937), 20.0, 100.0) ;
0.09556818::moveto_outcome(leg_try_goal, root, p18, success, point(22.275,2.745820393249937), 20.0, 100.0) ;
0.05841889::moveto_outcome(leg_try_goal, root, p19, success, point(22.945820393249935,2.745820393249937), 20.0, 100.0) ;
0.01464702::moveto_outcome(leg_try_goal, root, p20, success, point(23.61664078649987,2.745820393249937), 20.0, 100.0) ;
0.00367236::moveto_outcome(leg_try_goal, root, p21, success, point(20.933359213500125,3.4166407864998742), 20.0, 100.0) ;
0.01464702::moveto_outcome(leg_try_goal, root, p22, success, point(21.604179606750062,3.4166407864998742), 20.0, 100.0) ;
0.02396124::moveto_outcome(leg_try_goal, root, p23, success, point(22.275,3.4166407864998742), 20.0, 100.0) ;
0.01464702::moveto_outcome(leg_try_goal, root, p24, success, point(22.945820393249935,3.4166407864998742), 20.0, 100.0) ;
0.00367236::moveto_outcome(leg_try_goal, root, p25, success, point(23.61664078649987,3.4166407864998742), 20.0, 100.0).
