% AUTO-GENERATED by module/translators/bt_to_prolog.py from
% behavior_tree.xml -- DO NOT HAND-EDIT,
% edit the XML tree instead and regenerate (main.py does this
% automatically before every run).

plan(fallback_node([seq_node([cond(battery_over(70.0)),planWith(straight,point(22.275,2.075),CP),moveto_leg(CP,[collision,battery,battery_below(70)])]),seq_node([planWith(straight,point(2.275,2.075),CP2),moveto_leg(CP2,[collision,battery])])])).
