% AUTO-GENERATED by module/translators/bt_to_prolog.py from
% behavior_tree.xml -- DO NOT HAND-EDIT,
% edit the XML tree instead and regenerate (main.py does this
% automatically before every run).
%
% Action code legend (see main.py's own printed copy of this):
%   a1: PlanWith(astar, goal=point(0.5,0.0)) [MainTree]
%   a10: PlanWith(astar, goal=point(15.0,-18.0)) [MainTree]
%   a11: MoveTo(CP5) [MainTree]
%   a12: PlanWith(astar, goal=point(29.5,-22.5)) [MainTree]
%   a13: MoveTo(CP6) [MainTree]
%   a14: PlanWith(astar, goal=point(15.0,-27.0)) [MainTree]
%   a15: MoveTo(CP7) [MainTree]
%   a16: PlanWith(astar, goal=point(0.5,-22.5)) [MainTree]
%   a17: MoveTo(CP8) [MainTree]
%   a18: TakeSample(sample_tree_13) [MainTree]
%   a19: PlanWith(astar, goal=point(0.0,0.0)) [MainTree]
%   a2: MoveTo(CP1) [MainTree]
%   a20: MoveTo(CP9) [MainTree]
%   a21: PlanWith(astar, goal=point(9.0,27.0)) [MainTree]
%   a22: MoveTo(CP10) [MainTree]
%   a3: PlanWith(astar, goal=point(29.5,-4.5)) [MainTree]
%   a4: MoveTo(CP2) [MainTree]
%   a5: PlanWith(astar, goal=point(15.0,-9.0)) [MainTree]
%   a6: MoveTo(CP3) [MainTree]
%   a7: TakeSample(sample_tree_11) [MainTree]
%   a8: PlanWith(astar, goal=point(0.5,-13.5)) [MainTree]
%   a9: MoveTo(CP4) [MainTree]
%
% Condition code legend (see main.py's own printed copy of this):
%   c1: DistanceBelow(goal=0.5;0.0,threshold=0.3) [MainTree]
%   c10: DistanceBelow(goal=9.0;27.0,threshold=0.3) [MainTree]
%   c2: DistanceBelow(goal=29.5;-4.5,threshold=0.3) [MainTree]
%   c3: DistanceBelow(goal=15.0;-9.0,threshold=0.3) [MainTree]
%   c4: DistanceBelow(goal=0.5;-13.5,threshold=0.3) [MainTree]
%   c5: DistanceBelow(goal=15.0;-18.0,threshold=0.3) [MainTree]
%   c6: DistanceBelow(goal=29.5;-22.5,threshold=0.3) [MainTree]
%   c7: DistanceBelow(goal=15.0;-27.0,threshold=0.3) [MainTree]
%   c8: DistanceBelow(goal=0.5;-22.5,threshold=0.3) [MainTree]
%   c9: DistanceBelow(goal=0.0;0.0,threshold=0.3) [MainTree]

plan(seq_node([seq_node([seq_node([planWith(astar,point(0.5,0.0),CP1,a1),moveto_leg(CP1,[collision,battery],a2),cond(distance_below(0.5,0.0,0.3),c1)]),seq_node([planWith(astar,point(29.5,-4.5),CP2,a3),moveto_leg(CP2,[collision,battery],a4),cond(distance_below(29.5,-4.5,0.3),c2)]),seq_node([planWith(astar,point(15.0,-9.0),CP3,a5),moveto_leg(CP3,[collision,battery],a6),cond(distance_below(15.0,-9.0,0.3),c3)]),take_sample(sample_tree_11,a7),seq_node([planWith(astar,point(0.5,-13.5),CP4,a8),moveto_leg(CP4,[collision,battery],a9),cond(distance_below(0.5,-13.5,0.3),c4)]),seq_node([planWith(astar,point(15.0,-18.0),CP5,a10),moveto_leg(CP5,[collision,battery],a11),cond(distance_below(15.0,-18.0,0.3),c5)])]),seq_node([seq_node([planWith(astar,point(29.5,-22.5),CP6,a12),moveto_leg(CP6,[collision,battery],a13),cond(distance_below(29.5,-22.5,0.3),c6)]),seq_node([planWith(astar,point(15.0,-27.0),CP7,a14),moveto_leg(CP7,[collision,battery],a15),cond(distance_below(15.0,-27.0,0.3),c7)]),seq_node([planWith(astar,point(0.5,-22.5),CP8,a16),moveto_leg(CP8,[collision,battery],a17),cond(distance_below(0.5,-22.5,0.3),c8)]),take_sample(sample_tree_13,a18),seq_node([planWith(astar,point(0.0,0.0),CP9,a19),moveto_leg(CP9,[collision,battery],a20),cond(distance_below(0.0,0.0,0.3),c9)]),seq_node([planWith(astar,point(9.0,27.0),CP10,a21),moveto_leg(CP10,[collision,battery],a22),cond(distance_below(9.0,27.0,0.3),c10)])])])).
