% AUTO-GENERATED by module/translators/bt_to_prolog.py from
% behavior_tree.xml -- DO NOT HAND-EDIT,
% edit the XML tree instead and regenerate (main.py does this
% automatically before every run).
%
% Action code legend (see main.py's own printed copy of this):
%   a1: NearestToolOfKind(plow) [install_closest_plow]
%   a10: InstallTool({powlid__sub3}) [install_closest_plow]
%   a11: HitchedId [plowing]
%   a12: RetractTool({tool__sub2}) [plowing]
%   a13: PlanWith(astar, goal=point(14.0,0.0)) [plowing]
%   a14: MoveTo(CP1__SUB2) [plowing]
%   a15: DeployTool({tool__sub2}) [plowing]
%   a16: PlanWith(astar, goal=point(5.0,0.0)) [plowing]
%   a17: MoveTo(CP2__SUB2) [plowing]
%   a18: RetractTool({tool__sub2}) [plowing]
%   a19: HitchedId [uninstall_plow]
%   a2: PlanWith(astar, goal={powlposition__sub1}) [install_closest_plow]
%   a20: RetractTool({tool__sub4}) [uninstall_plow]
%   a21: PlanWith(astar, goal=point(18.5,-13.5)) [uninstall_plow]
%   a22: MoveTo(CP__SUB4) [uninstall_plow]
%   a23: UninstallTool({tool__sub4}) [uninstall_plow]
%   a24: PlanWith(astar, goal=point(0.0,-13.5)) [MainTree]
%   a25: MoveTo(CP2) [MainTree]
%   a3: MoveTo(CP__SUB1) [install_closest_plow]
%   a4: InstallTool({powlid__sub1}) [install_closest_plow]
%   a5: PlanWith(astar, goal=point(14.0,0.0)) [MainTree]
%   a6: MoveTo(CP1) [MainTree]
%   a7: NearestToolOfKind(plow) [install_closest_plow]
%   a8: PlanWith(astar, goal={powlposition__sub3}) [install_closest_plow]
%   a9: MoveTo(CP__SUB3) [install_closest_plow]
%
% Condition code legend (see main.py's own printed copy of this):
%   c1: Hitched(kind=plow) [install_closest_plow]
%   c2: PloughedBetween(p1=14;0,p2=5;0) [plowing]
%   c3: Hitched(kind=plow) [install_closest_plow]
%   c4: Deployed() [plowing]
%   c5: Hitched() [uninstall_plow]
%   c6: Deployed() [uninstall_plow]

plan(seq_node([fallback_node([cond(hitched(plow),c1),seq_node([nearest_tool_of_kind_query(plow,POWLID__SUB1,POWLPOSITION__SUB1,a1),planWith(astar,POWLPOSITION__SUB1,CP__SUB1,a2),moveto_leg(CP__SUB1,[collision,battery],a3),install_tool_leg(POWLID__SUB1,[battery],a4)])]),planWith(astar,point(14.0,0.0),CP1,a5),moveto_leg(CP1,[collision,battery],a6),fallback_node([cond(ploughed_between(14.0,0.0,5.0,0.0),c2),seq_node([fallback_node([cond(hitched(plow),c3),seq_node([nearest_tool_of_kind_query(plow,POWLID__SUB3,POWLPOSITION__SUB3,a7),planWith(astar,POWLPOSITION__SUB3,CP__SUB3,a8),moveto_leg(CP__SUB3,[collision,battery],a9),install_tool_leg(POWLID__SUB3,[battery],a10)])]),hitched_id_query(TOOL__SUB2,a11),fallback_node([inverter(cond(deployed,c4)),retract_tool_leg(TOOL__SUB2,[battery],a12)]),planWith(astar,point(14.0,0.0),CP1__SUB2,a13),moveto_leg(CP1__SUB2,[collision,battery],a14),deploy_tool_leg(TOOL__SUB2,[battery],a15),planWith(astar,point(5.0,0.0),CP2__SUB2,a16),moveto_leg(CP2__SUB2,[collision,battery],a17),retract_tool_leg(TOOL__SUB2,[battery],a18)])]),fallback_node([inverter(cond(hitched,c5)),seq_node([hitched_id_query(TOOL__SUB4,a19),fallback_node([inverter(cond(deployed,c6)),retract_tool_leg(TOOL__SUB4,[battery],a20)]),planWith(astar,point(18.5,-13.5),CP__SUB4,a21),moveto_leg(CP__SUB4,[collision,battery],a22),uninstall_tool_leg(TOOL__SUB4,[battery],a23)])]),planWith(astar,point(0.0,-13.5),CP2,a24),moveto_leg(CP2,[collision,battery],a25)])).
