% AUTO-GENERATED by module/translators/bt_to_prolog.py from
% behavior_tree.xml -- DO NOT HAND-EDIT,
% edit the XML tree instead and regenerate (main.py does this
% automatically before every run).
%
% Action code legend (see main.py's own printed copy of this):
%   a1: PlanWith(dastar(2.0), goal=point(11.3,-15.0)) [MainTree]
%   a2: MoveTo(CP1) [MainTree]
%   a3: PlanWithWaypoints(straight, waypoints=[(22.0,-15.0),(22.0,-3.3),(32.0,-3.3)]) [MainTree]
%   a4: MoveTo(CP2) [MainTree]
%   a5: TakeSample(sample_tree_11) [MainTree]
%   a6: PlanWithWaypoints(straight, waypoints=[(32.0,-27.0),(45.5,-27.0),(45.5,-36.0)]) [MainTree]
%   a7: MoveTo(CP3) [MainTree]
%
% Condition code legend (see main.py's own printed copy of this):
%   c1: BatteryBelow(threshold=50) [MainTree]
%   c2: DistanceBelow(goal=11.3;-15.0,threshold=1.0) [MainTree]
%   c3: DistanceBelow(goal=11.3;-15.0,threshold=1.0) [MainTree]
%   c4: DistanceBelow(goal=32.0;-3.3,threshold=1.0) [MainTree]
%   c5: DistanceBelow(goal=32.0;-3.3,threshold=1.0) [MainTree]
%   c6: DistanceBelow(goal=45.5;-36.0,threshold=1.0) [MainTree]
%   c7: DistanceBelow(goal=45.5;-36.0,threshold=1.0) [MainTree]

plan(reactivefallback(rc1)).

% One reactive_children/2 fact per <ReactiveSequence>/
% <ReactiveFallback> in the tree, keyed by the same code
% embedded in plan/1's own reactivesequence(Code)/
% reactivefallback(Code) markers above -- see basic_action_
% theory.pl's own CONTROL-FLOW REDESCEND TARGETS note for why
% these live as SEPARATE facts rather than being inlined.

reactive_children(rc1, [seq_node([cond(battery_below(50.0),c1),fallback_node([cond(distance_below(11.3,-15.0,1.0),c2),seq_node([planWith(dastar(2.0),point(11.3,-15.0),CP1,a1),moveto_leg(CP1,[collision,battery],a2),cond(distance_below(11.3,-15.0,1.0),c3)])])]),seq_node([fallback_node([cond(distance_below(32.0,-3.3,1.0),c4),seq_node([planWithWaypoints(straight,[point(22.0,-15.0),point(22.0,-3.3),point(32.0,-3.3)],CP2,a3),moveto_leg(CP2,[collision,battery],a4),cond(distance_below(32.0,-3.3,1.0),c5)])]),take_sample(sample_tree_11,a5),fallback_node([cond(distance_below(45.5,-36.0,1.0),c6),seq_node([planWithWaypoints(straight,[point(32.0,-27.0),point(45.5,-27.0),point(45.5,-36.0)],CP3,a6),moveto_leg(CP3,[collision,battery],a7),cond(distance_below(45.5,-36.0,1.0),c7)])])])]).
