% AUTO-GENERATED by module/translators/bt_to_prolog.py from
% behavior_tree.xml -- DO NOT HAND-EDIT,
% edit the XML tree instead and regenerate (main.py does this
% automatically before every run).
%
% Action code legend (see main.py's own printed copy of this):
%   a1: PlanWith(astar, goal=point(24.0,-4.5)) [MainTree]
%   a2: MoveTo(CP1) [MainTree]
%   a3: PlanWith(astar, goal=point(32.0,-4.5)) [MainTree]
%   a4: MoveTo(CP2) [MainTree]
%   a5: PlanWith(astar, goal=point(32.0,-27.0)) [MainTree]
%   a6: MoveTo(CP3) [MainTree]
%   a7: PlanWith(astar, goal=point(45.5,-31.5)) [MainTree]
%   a8: MoveTo(CP4) [MainTree]
%
% Condition code legend (see main.py's own printed copy of this):
%   c1: DistanceBelow(goal=24.0;-4.5,threshold=1.0) [MainTree]
%   c2: DistanceBelow(goal=24.0;-4.5,threshold=1.0) [MainTree]
%   c3: DistanceBelow(goal=32.0;-4.5,threshold=1.0) [MainTree]
%   c4: DistanceBelow(goal=32.0;-4.5,threshold=1.0) [MainTree]
%   c5: DistanceBelow(goal=32.0;-27.0,threshold=1.0) [MainTree]
%   c6: DistanceBelow(goal=32.0;-27.0,threshold=1.0) [MainTree]
%   c7: DistanceBelow(goal=45.5;-31.5,threshold=1.0) [MainTree]
%   c8: DistanceBelow(goal=45.5;-31.5,threshold=1.0) [MainTree]

plan(seq_node([fallback_node([cond(distance_below(24.0,-4.5,1.0),c1),seq_node([planWith(astar,point(24.0,-4.5),CP1,a1),moveto_leg(CP1,[collision,battery],a2),cond(distance_below(24.0,-4.5,1.0),c2)])]),fallback_node([cond(distance_below(32.0,-4.5,1.0),c3),seq_node([planWith(astar,point(32.0,-4.5),CP2,a3),moveto_leg(CP2,[collision,battery],a4),cond(distance_below(32.0,-4.5,1.0),c4)])]),fallback_node([cond(distance_below(32.0,-27.0,1.0),c5),seq_node([planWith(astar,point(32.0,-27.0),CP3,a5),moveto_leg(CP3,[collision,battery],a6),cond(distance_below(32.0,-27.0,1.0),c6)])]),fallback_node([cond(distance_below(45.5,-31.5,1.0),c7),seq_node([planWith(astar,point(45.5,-31.5),CP4,a7),moveto_leg(CP4,[collision,battery],a8),cond(distance_below(45.5,-31.5,1.0),c8)])])])).
