% AUTO-GENERATED by module/contracts/goal_formula_check.py's
% generate_safety_queries -- DO NOT HAND-EDIT, this is derived
% entirely from the problem's own behavior_tree.xml (via
% bt_to_prolog.py) and regenerated by main.py before every run.

query(verify_goal_formula).
query(plan_outcome(true)).
query(plan_outcome(false)).
query(plan_outcome(world_too_large)).
query(plan_outcome(reactive_escaped)).
query(outcome_signature(_)).

query(any_reason_pattern(battery_depleted)).
query(any_reason_pattern(completed)).
query(any_reason_pattern(completed(astar,[point(23.0,-36.0),point(0.5,-31.5),point(32.0,-4.5)]))).
query(any_reason_pattern(completed(astar,[point(24.0,-4.5),point(32.0,-4.5),point(32.0,-27.0),point(45.5,-31.5)]))).
query(any_reason_pattern(crashed(wild))).
query(any_reason_pattern(no_path(astar,[point(23.0,-36.0),point(0.5,-31.5),point(32.0,-4.5)]))).
query(any_reason_pattern(no_path(astar,[point(24.0,-4.5),point(32.0,-4.5),point(32.0,-27.0),point(45.5,-31.5)]))).
query(any_reason_pattern(sample_failure(wild,wild,sample_tree_11))).
query(any_reason_pattern(sample_failure(wild,wild,sample_tree_53))).
query(any_reason_pattern(sample_success(wild,wild,wild,sample_tree_11))).
query(any_reason_pattern(sample_success(wild,wild,wild,sample_tree_53))).

query(any_reason_pattern_by_action(completed(astar,[point(24.0,-4.5),point(32.0,-4.5),point(32.0,-27.0),point(45.5,-31.5)]),a1)).
query(any_reason_pattern_by_action(no_path(astar,[point(24.0,-4.5),point(32.0,-4.5),point(32.0,-27.0),point(45.5,-31.5)]),a1)).
query(any_reason_pattern_by_action(completed,a2)).
query(any_reason_pattern_by_action(crashed(wild),a2)).
query(any_reason_pattern_detail_by_action(crashed(_),a2)).
query(any_reason_pattern_by_action(battery_depleted,a2)).
query(any_reason_pattern_by_action(sample_success(wild,wild,wild,sample_tree_11),a3)).
query(any_reason_pattern_detail_by_action(sample_success(_,_,_,sample_tree_11),a3)).
query(any_reason_pattern_by_action(sample_failure(wild,wild,sample_tree_11),a3)).
query(any_reason_pattern_detail_by_action(sample_failure(_,_,sample_tree_11),a3)).
query(any_reason_pattern_by_action(completed(astar,[point(23.0,-36.0),point(0.5,-31.5),point(32.0,-4.5)]),a4)).
query(any_reason_pattern_by_action(no_path(astar,[point(23.0,-36.0),point(0.5,-31.5),point(32.0,-4.5)]),a4)).
query(any_reason_pattern_by_action(completed,a5)).
query(any_reason_pattern_by_action(crashed(wild),a5)).
query(any_reason_pattern_detail_by_action(crashed(_),a5)).
query(any_reason_pattern_by_action(battery_depleted,a5)).
query(any_reason_pattern_by_action(sample_success(wild,wild,wild,sample_tree_53),a6)).
query(any_reason_pattern_detail_by_action(sample_success(_,_,_,sample_tree_53),a6)).
query(any_reason_pattern_by_action(sample_failure(wild,wild,sample_tree_53),a6)).
query(any_reason_pattern_detail_by_action(sample_failure(_,_,sample_tree_53),a6)).

query(any_condition_status(c1,true)).
query(any_condition_status(c1,false)).
query(any_condition_status(c2,true)).
query(any_condition_status(c2,false)).
query(any_condition_status(c3,true)).
query(any_condition_status(c3,false)).
query(any_condition_status(c4,true)).
query(any_condition_status(c4,false)).
