% AUTO-GENERATED by module/translators/bt_to_prolog.py from
% behavior_tree.xml -- DO NOT HAND-EDIT,
% edit the XML tree instead and regenerate (main.py does this
% automatically before every run).
%
% Action code legend (see main.py's own printed copy of this):
%   a1: PlanWithWaypoints(straight, waypoints=[(22.0,-15.0),(22.0,-3.3),(32.0,-3.3),(32.0,18.0)]) [MainTree]
%   a2: MoveTo(CP1) [MainTree]
%   a3: TakeSample(sample_tree_11) [MainTree]
%   a4: PlanWithWaypoints(straight, waypoints=[(45.5,18.0),(23.0,18.0),(0.5,18.0),(0.5,27.0),(23.0,27.0),(45.5,27.0)]) [MainTree]
%   a5: MoveTo(CP2) [MainTree]
%   a6: TakeSample(sample_tree_53) [MainTree]
%
% Condition code legend (see main.py's own printed copy of this):
%   c1: DistanceBelow(goal=32.0;18.0,threshold=1.0) [MainTree]
%   c2: DistanceBelow(goal=32.0;18.0,threshold=1.0) [MainTree]
%   c3: DistanceBelow(goal=45.5;27.0,threshold=1.0) [MainTree]
%   c4: DistanceBelow(goal=45.5;27.0,threshold=1.0) [MainTree]

plan(seq_node([fallback_node([cond(distance_below(32.0,18.0,1.0),c1),seq_node([planWithWaypoints(straight,[point(22.0,-15.0),point(22.0,-3.3),point(32.0,-3.3),point(32.0,18.0)],CP1,a1),moveto_leg(CP1,[collision,battery],a2),cond(distance_below(32.0,18.0,1.0),c2)])]),take_sample(sample_tree_11,a3),fallback_node([cond(distance_below(45.5,27.0,1.0),c3),seq_node([planWithWaypoints(straight,[point(45.5,18.0),point(23.0,18.0),point(0.5,18.0),point(0.5,27.0),point(23.0,27.0),point(45.5,27.0)],CP2,a4),moveto_leg(CP2,[collision,battery],a5),cond(distance_below(45.5,27.0,1.0),c4)])]),take_sample(sample_tree_53,a6)])).
