% AUTO-GENERATED by module/translators/bt_to_prolog.py from
% behavior_tree.xml -- DO NOT HAND-EDIT,
% edit the XML tree instead and regenerate (main.py does this
% automatically before every run).
%
% Action code legend (see main.py's own printed copy of this):
%   a1: NearestToolOfKind(plow) [install_closest_plow]
%   a10: RetractTool({tool__sub2}) [plowing]
%   a11: PlanWith(astar, goal=point(5.0,-9.0)) [plowing]
%   a12: MoveTo(CP1__SUB2) [plowing]
%   a13: DeployTool({tool__sub2}) [plowing]
%   a14: PlanWith(astar, goal=point(25.0,-9.0)) [plowing]
%   a15: MoveTo(CP2__SUB2) [plowing]
%   a16: RetractTool({tool__sub2}) [plowing]
%   a17: HitchedId [uninstall_plow]
%   a18: RetractTool({tool__sub4}) [uninstall_plow]
%   a19: PlanWith(astar, goal=point(29.5,0.0)) [uninstall_plow]
%   a2: PlanWith(astar, goal={powlposition__sub1}) [install_closest_plow]
%   a20: MoveTo(CP__SUB4) [uninstall_plow]
%   a21: UninstallTool({tool__sub4}) [uninstall_plow]
%   a3: MoveTo(CP__SUB1) [install_closest_plow]
%   a4: InstallTool({powlid__sub1}) [install_closest_plow]
%   a5: NearestToolOfKind(plow) [install_closest_plow]
%   a6: PlanWith(astar, goal={powlposition__sub3}) [install_closest_plow]
%   a7: MoveTo(CP__SUB3) [install_closest_plow]
%   a8: InstallTool({powlid__sub3}) [install_closest_plow]
%   a9: HitchedId [plowing]
%
% Condition code legend (see main.py's own printed copy of this):
%   c1: Hitched(kind=plow) [install_closest_plow]
%   c2: PloughedBetween(p1=5.0;-9.0,p2=25.0;-9.0) [plowing]
%   c3: Hitched(kind=plow) [install_closest_plow]
%   c4: Deployed() [plowing]
%   c5: Hitched() [uninstall_plow]
%   c6: Deployed() [uninstall_plow]

plan(seq_node([fallback_node([cond(hitched(plow),c1),seq_node([nearest_tool_of_kind_query(plow,POWLID__SUB1,POWLPOSITION__SUB1,a1),planWith(astar,POWLPOSITION__SUB1,CP__SUB1,a2),moveto_leg(CP__SUB1,[collision,battery],a3),install_tool_leg(POWLID__SUB1,[battery],a4)])]),fallback_node([cond(ploughed_between(5.0,-9.0,25.0,-9.0),c2),seq_node([fallback_node([cond(hitched(plow),c3),seq_node([nearest_tool_of_kind_query(plow,POWLID__SUB3,POWLPOSITION__SUB3,a5),planWith(astar,POWLPOSITION__SUB3,CP__SUB3,a6),moveto_leg(CP__SUB3,[collision,battery],a7),install_tool_leg(POWLID__SUB3,[battery],a8)])]),hitched_id_query(TOOL__SUB2,a9),fallback_node([inverter(cond(deployed,c4)),retract_tool_leg(TOOL__SUB2,[battery],a10)]),planWith(astar,point(5.0,-9.0),CP1__SUB2,a11),moveto_leg(CP1__SUB2,[collision,battery],a12),deploy_tool_leg(TOOL__SUB2,[battery],a13),planWith(astar,point(25.0,-9.0),CP2__SUB2,a14),moveto_leg(CP2__SUB2,[collision,battery],a15),retract_tool_leg(TOOL__SUB2,[battery],a16)])]),fallback_node([inverter(cond(hitched,c5)),seq_node([hitched_id_query(TOOL__SUB4,a17),fallback_node([inverter(cond(deployed,c6)),retract_tool_leg(TOOL__SUB4,[battery],a18)]),planWith(astar,point(29.5,0.0),CP__SUB4,a19),moveto_leg(CP__SUB4,[collision,battery],a20),uninstall_tool_leg(TOOL__SUB4,[battery],a21)])])])).
