% AUTO-GENERATED by plan_generation/bt_to_prolog.py from
% behavior_tree.xml -- DO NOT HAND-EDIT,
% edit the XML tree instead and regenerate (run_plan_continuous_safety.py
% does this automatically before every run).

plan(seq_node([planWith(astar,point(11.675,11.525),CP),moveto_leg(CP,[collision,battery])])).
