% AUTO-GENERATED by module/translators/bt_to_prolog.py from
% behavior_tree.xml -- DO NOT HAND-EDIT,
% edit the XML tree instead and regenerate (main.py does this
% automatically before every run).
%
% Action code legend (see main.py's own printed copy of this):
%   a1: PlanWith(astar, goal=point(24.0,-4.5)) [MainTree]
%   a2: MoveTo(CP1) [MainTree]
%   a3: PlanWith(astar, goal=point(32.0,-4.5)) [MainTree]
%   a4: MoveTo(CP2) [MainTree]
%   a5: PlanWith(astar, goal=point(32.0,-27.0)) [MainTree]
%   a6: MoveTo(CP3) [MainTree]
%
% Condition code legend (see main.py's own printed copy of this):
%   c1: DistanceBelow(goal=24.0;-4.5,threshold=0.3) [MainTree]
%   c2: DistanceBelow(goal=32.0;-4.5,threshold=0.3) [MainTree]
%   c3: DistanceBelow(goal=32.0;-27.0,threshold=0.3) [MainTree]

plan(seq_node([seq_node([planWith(astar,point(24.0,-4.5),CP1,a1),moveto_leg(CP1,[collision,battery],a2),cond(distance_below(24.0,-4.5,0.3),c1)]),seq_node([planWith(astar,point(32.0,-4.5),CP2,a3),moveto_leg(CP2,[collision,battery],a4),cond(distance_below(32.0,-4.5,0.3),c2)]),seq_node([planWith(astar,point(32.0,-27.0),CP3,a5),moveto_leg(CP3,[collision,battery],a6),cond(distance_below(32.0,-27.0,0.3),c3)])])).
